version: "3.8"

services:
  app:
    build: .
    container_name: doo-store
    restart: unless-stopped
    # privileged: true
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      SQLITE_PATH: "./db/app.db"
      DATA_DIR: "/app/docker/dood"
      APP_ID: "${APP_ID}"
      PLUGIN_CIDR: "${APP_IPPR}.30/24"
      DOOTASK_DIR: "${PWD}"
      DOOTASK_APP_ID: "${APP_ID}"
      DOOTASK_NETWORK_NAME: "dootask-networks-${APP_ID}"
      DOOTASK_APP_IPPR: "${APP_IPPR}"

    volumes:
      - ./docker/sqlite:/app/db
      - ./docker/init:/app/init
      - ./docker/dood:/app/docker/dood
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.18"

networks:
  extnetwork:
    name: "dootask-networks-${APP_ID}"
    external: true
