definitions:
  dto.EnvElement:
    properties:
      key:
        type: string
      name:
        type: string
      required:
        type: boolean
      type:
        type: string
      value:
        type: string
    type: object
  dto.PageResult:
    properties:
      items: {}
      total:
        type: integer
    type: object
  dto.Response:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg:
        example: success
        type: string
    type: object
  dto.Volume:
    properties:
      local:
        type: string
      target:
        type: string
    type: object
  model.App:
    properties:
      class:
        type: string
      created_at:
        type: string
      depends_version:
        type: string
      description:
        type: string
      github:
        type: string
      icon:
        type: string
      id:
        type: integer
      key:
        type: string
      name:
        type: string
      sort:
        type: integer
      status:
        type: string
      updated_at:
        type: string
    type: object
  model.Tag:
    properties:
      created_at:
        type: string
      id:
        type: integer
      key:
        type: string
      name:
        type: string
      sort:
        type: integer
      updated_at:
        type: string
    type: object
  request.AppInstall:
    properties:
      cpus:
        type: string
      docker_compose:
        type: string
      memory_limit:
        type: string
      params:
        additionalProperties: true
        type: object
    required:
    - cpus
    - docker_compose
    - memory_limit
    - params
    type: object
  request.AppInstalledOperate:
    properties:
      action:
        type: string
      params:
        additionalProperties: true
        type: object
    type: object
  request.AppUnInstall:
    type: object
  request.PluginUpload:
    properties:
      class:
        type: string
      command:
        type: string
      depends_version:
        type: string
      description:
        type: string
      docker_compose:
        type: string
      env:
        items:
          $ref: '#/definitions/dto.EnvElement'
        type: array
      github:
        type: string
      icon:
        type: string
      key:
        type: string
      name:
        type: string
      nginx_config:
        type: string
      repo:
        type: string
      version:
        type: string
      volume:
        items:
          $ref: '#/definitions/dto.Volume'
        type: array
    type: object
  response.AppDetail:
    properties:
      app_id:
        type: integer
      created_at:
        type: string
      depends_version:
        type: string
      docker_compose:
        type: string
      id:
        type: integer
      nginx_config:
        type: string
      params:
        $ref: '#/definitions/response.AppParams'
      repo:
        type: string
      status:
        type: string
      updated_at:
        type: string
      version:
        type: string
    type: object
  response.AppInstalledParamsResp:
    properties:
      cpus:
        type: string
      docker_compose:
        type: string
      memory_limit:
        type: string
      params:
        items:
          $ref: '#/definitions/response.FormField'
        type: array
    type: object
  response.AppParams:
    properties:
      form_fields:
        items:
          $ref: '#/definitions/response.FormField'
        type: array
    type: object
  response.FormField:
    properties:
      default:
        type: string
      env_key:
        type: string
      key:
        type: string
      label:
        type: string
      required:
        type: boolean
      rule:
        type: string
      type:
        type: string
      value:
        type: string
      values: {}
    type: object
info:
  contact:
    email: xxyijixx@gmail.com
    name: xxyijixx
  description: Description of Doo Store API documentation
  license:
    name: AGPL-3.0
    url: https://opensource.org/license/agpl-v3
  title: Doo Store API Documentation
  version: "1.0"
paths:
  /apps:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: page_size
        in: query
        name: page_size
        required: true
        type: integer
      - description: class
        in: query
        name: class
        type: string
      - description: name
        in: query
        name: name
        type: string
      - description: id
        in: query
        name: id
        type: integer
      - description: description
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dto.PageResult'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/model.App'
                        type: array
                    type: object
              type: object
      security:
      - BearerAuth: []
      summary: 获取插件列表
      tags:
      - app
  /apps/{key}:
    delete:
      consumes:
      - application/json
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppUnInstall'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: 插件卸载
      tags:
      - app
    post:
      consumes:
      - application/json
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppInstall'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: 插件安装
      tags:
      - app
    put:
      consumes:
      - application/json
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppInstalledOperate'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: app update
      tags:
      - app
  /apps/{key}/detail:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AppDetail'
              type: object
      security:
      - BearerAuth: []
      summary: 获取插件详情
      tags:
      - app
  /apps/installed:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: page_size
        in: query
        name: page_size
        required: true
        type: integer
      - description: 分类
        in: query
        name: class
        type: string
      - description: name
        in: query
        name: name
        type: string
      - description: description
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dto.PageResult'
                  - properties:
                      items:
                        items:
                          type: object
                        type: array
                    type: object
              type: object
      security:
      - BearerAuth: []
      summary: 获取已安装插件列表
      tags:
      - app
  /apps/installed/{id}/logs:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: 开始时间(Unix时间戳，秒)
        in: query
        name: since
        type: integer
      - description: 结束时间(Unix时间戳，秒)
        in: query
        name: until
        type: integer
      - default: 1000
        description: 查询条数
        in: query
        name: tail
        required: true
        type: integer
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: 获取插件日志信息
      tags:
      - app
  /apps/installed/{id}/params:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AppInstalledParamsResp'
              type: object
      security:
      - BearerAuth: []
      summary: 获取插件参数信息
      tags:
      - app
    put:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AppInstall'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: 修改插件参数信息
      tags:
      - app
  /apps/manage/upload:
    post:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: RequestBody
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PluginUpload'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - BearerAuth: []
      summary: 上传插件
      tags:
      - app
  /apps/plugin/info:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      - description: key
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                additionalProperties: {}
                type: object
              msg:
                type: string
              ret:
                type: string
            type: object
      security:
      - BearerAuth: []
      summary: 获取已安装的插件信息(仅需要登录)
      tags:
      - app
  /apps/tags:
    get:
      parameters:
      - default: zh
        description: i18n
        in: header
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Tag'
                  type: array
              type: object
      security:
      - BearerAuth: []
      summary: 获取插件分类信息
      tags:
      - app
  /public/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: health
      tags:
      - public
securityDefinitions:
  BearerAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
